export const GithubImageTools_REPO_NAME = 'XPoet/GithubImageTools'
export const INIT_REPO_NAME = 'GithubImageTools-images-hosting'
export const INIT_REPO_DESC = 'GithubImageTools images hosting repository'
export const INIT_REPO_BARNCH = 'master'
export const GithubImageTools_UPLOAD_IMG_DESC = 'Upload image via GithubImageTools(https://github.com/XPoet/GithubImageTools)'
export const GithubImageTools_UPLOAD_IMGS_DESC = 'Upload images via GithubImageTools(https://github.com/XPoet/GithubImageTools)'
export const GithubImageTools_DEL_IMG_DESC = 'Delete image via GithubImageTools(https://github.com/XPoet/GithubImageTools)'
